logging:
  file:
    name: Shopmmt-frontend.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: Shopmmt-frontend-%d{dd-MM-yyyy}.%i.log
      max-file-size: 100KB
      max-history: 14
      total-size-cap: 1MB
server:
  port: 80
#  servlet:
    #context-path: /Shopmmt
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/shopmmtdb
    username: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: true
        format_sql: true
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 830986015811-76eldfmfh6tnl19bgc2b583ft6qh0nds.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 389261093506615
            client-secret: 7bf7358c5766eb2ea1ad20ac22801d5f
            scope:
            - email
            - public_profile
  servlet:
    multipart:
      max-file-size: 3MB
